# Generated by Django 5.2.7 on 2026-05-28 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionGroup",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=120)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("PARALLEL_LAB", "Parallel lab"),
                            ("COMMON_ELECTIVE", "Common elective"),
                        ],
                        max_length=30,
                    ),
                ),
                ("same_time_required", models.BooleanField(default=True)),
                ("same_building_required", models.BooleanField(default=False)),
                (
                    "preferred_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_session_groups",
                        to="infrastructure.building",
                    ),
                ),
            ],
            options={
                "db_table": "session_group",
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "required_room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LAB", "Lab"),
                            ("ANY", "Any"),
                        ],
                        default="CLASSROOM",
                        max_length=20,
                    ),
                ),
                ("priority_level", models.PositiveSmallIntegerField(default=3)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="accounts.faculty",
                    ),
                ),
                (
                    "preferred_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_assignments",
                        to="infrastructure.room",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "teaching_assignment",
            },
        ),
        migrations.CreateModel(
            name="SessionGroupMember",
            fields=[
                (
                    "group_member_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="timetables.sessiongroup",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_groups",
                        to="timetables.teachingassignment",
                    ),
                ),
            ],
            options={
                "db_table": "session_group_member",
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "timetable_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_timetables",
                        to="accounts.appuser",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="academics.section",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetables",
                        to="academics.academicterm",
                    ),
                ),
            ],
            options={
                "db_table": "timetable",
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                ("entry_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("duration", models.PositiveSmallIntegerField(default=1)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("SUBSTITUTE", "Substitute"),
                            ("EXTRA_CLASS", "Extra class"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CANCELLED", "Cancelled"),
                            ("MODIFIED", "Modified"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="timetables.teachingassignment",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="infrastructure.day",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_entries",
                        to="infrastructure.room",
                    ),
                ),
                (
                    "starting_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_entries",
                        to="infrastructure.timeslot",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="timetables.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "timetable entries",
                "db_table": "timetable_entry",
            },
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(
                fields=("section", "subject", "faculty"),
                name="unique_teaching_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessiongroupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "assignment"), name="unique_session_group_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("section", "term", "version_number"),
                name="unique_timetable_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("timetable", "day", "starting_slot", "assignment"),
                name="unique_assignment_slot_per_timetable",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("day", "starting_slot", "room"),
                name="unique_scheduled_room_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("day", "starting_slot", "assignment"),
                name="unique_scheduled_assignment_slot",
            ),
        ),
    ]
