# Generated by Django 5.2.7 on 2026-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_alter_department_department_name_and_more"),
        ("accounts", "0001_initial"),
        ("infrastructure", "0002_timeslot_unique_timeslot_time_range"),
        ("timetables", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="unique_scheduled_room_slot",
        ),
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="unique_scheduled_assignment_slot",
        ),
        migrations.AlterField(
            model_name="sessiongroup",
            name="group_name",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PUBLISHED")),
                fields=("section", "term"),
                name="unique_published_timetable_per_section_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("timetable", "day", "starting_slot"),
                name="unique_scheduled_section_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("timetable", "day", "starting_slot", "room"),
                name="unique_scheduled_room_slot_per_timetable",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SCHEDULED")),
                fields=("timetable", "day", "starting_slot", "assignment"),
                name="unique_scheduled_assignment_slot_per_timetable",
            ),
        ),
    ]
