# Generated by Django 5.2.7 on 2026-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "timetables",
            "0002_remove_timetableentry_unique_scheduled_room_slot_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessiongroup",
            name="group_type",
        ),
        migrations.AddField(
            model_name="sessiongroup",
            name="group_category",
            field=models.CharField(
                choices=[
                    ("PARALLEL_LAB", "Parallel lab"),
                    ("COMMON_ELECTIVE", "Common elective"),
                ],
                default="PARALLEL_LAB",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sessiongroup",
            name="priority_level",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="teachingassignment",
            name="required_room_type",
            field=models.CharField(
                choices=[
                    ("CLASSROOM", "Classroom"),
                    ("COMPUTER_LAB", "Computer lab"),
                    ("HARDWARE_LAB", "Hardware lab"),
                    ("SEMINAR_HALL", "Seminar hall"),
                    ("ANY", "Any"),
                ],
                default="CLASSROOM",
                max_length=20,
            ),
        ),
    ]
