# Generated by Django 5.2.7 on 2026-05-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstraintType",
            fields=[
                (
                    "constraint_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("constraint_name", models.CharField(max_length=120, unique=True)),
                ("constraint_category", models.CharField(max_length=80)),
                ("priority_level", models.PositiveSmallIntegerField(default=3)),
                ("is_hard_constraint", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "constraint_type",
            },
        ),
        migrations.CreateModel(
            name="FacultyConstraint",
            fields=[
                (
                    "constraint_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "constraint_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_constraints",
                        to="constraints.constrainttype",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_constraints",
                        to="infrastructure.day",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="accounts.faculty",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_constraints",
                        to="infrastructure.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "faculty_constraint",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faculty", "day", "slot", "constraint_type"),
                        name="unique_faculty_constraint",
                    )
                ],
            },
        ),
    ]
