# Generated by Django 5.2.7 on 2026-05-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("FACULTY", "Faculty")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "app_user",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("faculty_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("faculty_name", models.CharField(max_length=120)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty",
                        to="academics.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_profile",
                        to="accounts.appuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faculty",
                "db_table": "faculty",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "roll_no",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("student_name", models.CharField(max_length=120)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academics.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="accounts.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
