# Generated by Django 5.2.7 on 2026-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("ADMIN", "Admin"),
                    ("HOD", "HOD"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
