# Generated by Django 5.2.7 on 2026-06-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_remove_subject_lecture_hours_and_more"),
        ("accounts", "0003_appuser_auth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="academics.section",
            ),
        ),
    ]
