# Generated by Django 5.2.7 on 2026-05-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("building_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("building_name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "db_table": "building",
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                ("day_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day_name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "day",
            },
        ),
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                ("slot_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("slot_number", models.PositiveSmallIntegerField(unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_break", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "timeslot",
                "ordering": ["slot_number"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LAB", "Lab"),
                            ("SEMINAR", "Seminar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "db_table": "room",
            },
        ),
    ]
