# Generated by Django 5.2.7 on 2026-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("start_time", "end_time"), name="unique_timeslot_time_range"
            ),
        ),
    ]
