# Generated by Django 5.2.7 on 2026-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_remove_subject_lecture_hours_and_more"),
        ("infrastructure", "0002_timeslot_unique_timeslot_time_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("CLASSROOM", "Classroom"),
                    ("COMPUTER_LAB", "Computer lab"),
                    ("HARDWARE_LAB", "Hardware lab"),
                    ("SEMINAR_HALL", "Seminar hall"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("building", "room_name"), name="unique_room_name_per_building"
            ),
        ),
    ]
