# Generated by Django 5.2.7 on 2026-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0003_room_room_name_alter_room_room_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=80),
        ),
    ]
