# Generated by Django 5.2.7 on 2026-05-28 11:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0004_alter_room_room_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="day",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("day_name"),
                name="unique_day_name_case_insensitive",
            ),
        ),
    ]
