# Generated by Django 5.2.7 on 2026-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("department_code", models.CharField(max_length=20, unique=True)),
                ("department_name", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year_number", models.PositiveSmallIntegerField()),
                ("section_name", models.CharField(max_length=20)),
                ("student_strength", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "section",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("subject_title", models.CharField(max_length=160)),
                ("credits", models.PositiveSmallIntegerField()),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("THEORY", "Theory"),
                            ("LAB", "Lab"),
                            ("THEORY_LAB", "Theory + Lab"),
                        ],
                        default="THEORY",
                        max_length=20,
                    ),
                ),
                ("lecture_hours", models.PositiveSmallIntegerField(default=0)),
                ("tutorial_hours", models.PositiveSmallIntegerField(default=0)),
                ("practical_hours", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                ("term_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "term_type",
                    models.CharField(
                        choices=[("ODD", "Odd"), ("EVEN", "Even")], max_length=10
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "academic_term",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year", "term_type"),
                        name="unique_academic_year_term_type",
                    )
                ],
            },
        ),
    ]
