# Generated by Django 5.2.7 on 2026-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hod__isnull", False)),
                fields=("hod",),
                name="unique_department_hod",
            ),
        ),
    ]
