# Generated by Django 5.2.7 on 2026-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_alter_department_department_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="lecture_hours",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="practical_hours",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="tutorial_hours",
        ),
        migrations.AddField(
            model_name="subject",
            name="required_room_type",
            field=models.CharField(
                choices=[
                    ("CLASSROOM", "Classroom"),
                    ("COMPUTER_LAB", "Computer lab"),
                    ("HARDWARE_LAB", "Hardware lab"),
                    ("SEMINAR_HALL", "Seminar hall"),
                ],
                default="CLASSROOM",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="session_duration",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="sessions_per_week",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[("THEORY", "Theory"), ("LAB", "Lab"), ("SEMINAR", "Seminar")],
                default="THEORY",
                max_length=20,
            ),
        ),
    ]
